### ISSUE TITLE
v0.6计划

### ISSUE THREAD

**Issue by Blinue** [Blinue/Magpie#12]
- [x] 使用WPF重构用户界面
- [x] 关于
- [x] 开机启动
- [x] 监视ScaleModels.json的更改
- [x] 将C++依赖迁移到[Conan](https://conan.io/)
- [x] 增加版本号管理
- [x] 支持在源窗口重获焦点时自动进入全屏
#16 
- [x] 支持英语（English support）
#10 
#33 
- [ ] ~~改进现有着色器，缓解压缩造成的精度损失~~（暂时不修复）
- [x] 改进错误处理，添加日志记录（Runtime无日志，因为计划在下个版本重写）

**Comment by DefectiveByDesign** [comment]
Can you add FSR to the list? There's a lot of benefits to FSR, it's designed for this function, open source, broad compatibility, and high performance.
https://gpuopen.com/fidelityfx-superresolution/

**Comment by canceralp** [comment]
Would you mind adding a way to use Reshade with Magpie so, upscaled games can have Reshade shaders at upscaled resolutions? 

For Example:
Game resoltuion = 1920x1080
Magpie upscales to = 3840x2160
Reshade runs on Magpie and,
Reshade effects (like FXAA) = 3840x2160

This way a game can have 2 Reshades. One operates at the game's own resolution, the other one operates on Magpie at higher (upscaled) resolution. 

Thank you for this nice software, BTW.

**Comment by Blinue** [comment]
Feel free to post a new issue😉

**Comment by Gabri3445** [comment]
Is there going to be support for adding other languages? I'd be able to help with an Italian translation.

**Comment by Blinue** [comment]
Sure! I'll post a contribution guide once I've prepared the text to be translated

**Comment by heroutm** [comment]
> Sure! I'll post a contribution guide once I've prepared the text to be translated
I can also help you with translation.

**Comment by motoleon** [comment]
I can help with Spanish Translation...

**Comment by ButtERRbrod** [comment]
I could help you with Russian translation ;)

**Comment by franvmm** [comment]
there are troubles with games like raceroom racing experience, crashing at start, and loosing mouse on screen

**Comment by Blinue** [comment]
The easiest way to recover is to restart your computer, [here](https://github.com/Blinue/Magpie/issues/24#issuecomment-891640638) is another way.

Please post an issue if Magpie doesn't work.
