### ISSUE TITLE
v0.8 计划

### ISSUE THREAD

**Issue by Blinue** [Blinue/Magpie#202]
- [x] 用户界面迁移到 .NET 6
- [x] 支持裁剪 UWP 的非客户区
- [x] 为 FPS 显示添加阴影
#111
- [x] 移植 [NIS](https://github.com/NVIDIAGameWorks/NVIDIAImageScaling)
- [x] 移植 CRT 着色器（~~crt-royale~~ 等）
#160 
- [x] 移植 luma-sharpen 和 finesharp
- [x] DX10 版本

### 多屏幕

- [x] 支持在 DPI 缩放不同的多屏上工作
- [x] 支持跨越多个屏幕
#219
- [x] 支持在全屏时将光标移出屏幕
#65

**Comment by hooke007** [comment]
https://github.com/Blinue/Magpie/blob/a69f902713e4e211e480986229d112d0166ca618/Runtime/effects/RAVU_Zoom_R3.hlsl#L74-L75
我看到了这段注释，想起来之前给mpv报错的时候提过，希望有帮助。
https://github.com/mpv-player/mpv/issues/9390#issuecomment-961082863
最终上游的修复也是一样
https://github.com/bjin/mpv-prescalers/commit/267863074bc6e3f147bf9bca34d703445f075f60

**Comment by Blinue** [comment]
感谢 https://github.com/Blinue/Magpie/commit/69fe0cf9cac47196edd004713b0fff069d847f12

**Comment by motoleon** [comment]
Use with youtube???

**Comment by hooke007** [comment]
> Use with youtube???

Now u can do it. PIP function of modern browser would create the another window for webvideo.

But why not use media player?

**Comment by Blinue** [comment]
英伟达刚开源了 [NIS](https://github.com/NVIDIAGameWorks/NVIDIAImageScaling)，一个和 FSR 竞争的技术。我会尝试移植它

**Comment by palxex** [comment]
@Blinue FSR的官方demo看起来也是用compute shader做的，请问NIS的做法是与之有什么差异，以致无法用同样的方法移植吗？还是说FSR本身就预留了两种调用路径。

**Comment by Blinue** [comment]
FSR 同时支持像素和计算着色器，NIS 从源码看移植到像素着色器没有太大的问题。我最近会进行移植

**Comment by LightMu** [comment]
进显卡控制面板了，普及比FSR快多了，基本直接实现通用，感觉老黄又赢了。

**Comment by jovan2009** [comment]
As it runs inside driver NIS theoretically should be better. But it is not, I can't get low latency without tearing. Using RTSS fps limiter + sync limiter + fast vsync I get tearing with NIS, which is amazing, fast vsync should be free of tearing. On the other hand Magpie works very well in the same setup. On my gtx 1050ti NIS take about same percentage of GPU utilisation like FSR, maybe a little higher, but tearing is kind of deal breaker.

**Comment by hooke007** [comment]
从LS的实现来看，不出意外和fsr一样，空间放大都是基于bilinear没有亮点，至少从效果看是这样的，不加锐化也表现大体相似，感知上区分是靠比cas激进的锐化步骤

**Comment by Blinue** [comment]
release/v0.7 实现了指定 GPU 的功能，你们能正常使用吗 @palxex @hooke007 

直接从 Actions 下载：https://github.com/Blinue/Magpie/actions/runs/1484391093

**Comment by palxex** [comment]
> release/v0.7 实现了指定 GPU 的功能，你们能正常使用吗
抱歉，我用的是amd 3600，没核显。

**Comment by LightMu** [comment]
![image](https://user-images.githubusercontent.com/88380761/142725928-c7d674a6-cb56-4c37-ad78-34691dd6331a.png)

**Comment by Blinue** [comment]
这个选项可以正常使用吗 @LightMu

**Comment by hooke007** [comment]
我这是独显直连，核显屏蔽后只显示两项，指定microsoft也工作正常，cpu占用会大幅上升

**Comment by Blinue** [comment]
最后一个选项是 [WARP](https://docs.microsoft.com/en-us/windows/win32/direct3darticles/directx-warp)，纯 CPU 渲染

**Comment by LightMu** [comment]
我这里是笔记本，不支持独显直连。我外接了副屏，相当于独显直连。都正常使用

**Comment by Blinue** [comment]
> DSS不工作（意思是保持窗口模式不动弹）

看起来 WARP 和 DwmSharedSurface 不兼容

**Comment by linserv33** [comment]
这边是笔记本，支持独显直连，试着切换混合模式用集显运行任务管理器观察占用情况，无论是在windows图像设置独显优先，还是在nvidia里设置独显优先的情况下，只要在magpie里设定对应显卡，他就会按对应显卡运行
相关设置
![新建 BMP 图像](https://user-images.githubusercontent.com/81668816/142728352-05bc1784-694e-4baf-99c0-6b05a6acb06b.png)
![1](https://user-images.githubusercontent.com/81668816/142728377-73a751bf-2ef9-4322-b204-593964658df9.png)
任务管理器截图
![屏幕截图(1)](https://user-images.githubusercontent.com/81668816/142728390-f1058351-6762-4783-b718-d06e20f13c34.png)

这边显卡切换功能貌似就是给magpie接管了

**Comment by Blinue** [comment]
Magpie 现已支持 DPI 缩放不同的多显示器。

2021 年了 WPF 依然没有原生的支持，从提交上看 WPF 的开发处于停滞状态 https://github.com/dotnet/wpf/commits/main

**Comment by Blinue** [comment]
Win11 的新表情很有意思
# MAG:mag:IE

**Comment by Blinue** [comment]
NIS 比 FSR 锐利的多。移植为像素着色器后 NIS 非常慢，还需要优化一下

https://imgsli.com/ODM4Mzg

**Comment by Blinue** [comment]
NIS 附带一个 NVSharpen，和 FSR_EASU 是很好的组合。既有 FSR 的速度，又有 NIS 的锐度。

对比：https://imgsli.com/ODM5MDM

**Comment by linserv33** [comment]
看起来十分不错！

**Comment by linserv33** [comment]
发现一个现象，LS移植的NIS锐化效果不如驱动的锐化效果，表现有些糟糕（没有驱动锐化的清晰），看了你的对比，貌似和驱动没什么太大区别

**Comment by Blinue** [comment]
锐度可通过 sharpness 参数调整

**Comment by palxex** [comment]
@Blinue 请问是这么设置吗？
```
  {
    "name": "NIS",
    "effects": [
      {
        "effect": "NIS",
        "scale": [ -1, -1 ],
        "sharpness": 0.5
      }
    ]
  },
  {
    "name": "EASU+NVSharpen",
    "effects": [
      {
        "effect": "FSR_EASU",
        "scale": [ -1, -1 ]
      },
      {
        "effect": "NVSharpen",
        "sharpness": 0.5
      }
    ]
  },
```
现在在办公电脑上没条件拿游戏测，用magpie主界面缩放了下感觉差别还挺大的
![1](https://user-images.githubusercontent.com/58222/143824492-30de42ff-778b-4c23-8625-f70b22422177.png)
![2](https://user-images.githubusercontent.com/58222/143824504-e97a3c56-e16b-48fb-b95c-7cee1b7403a7.png)

**Comment by Blinue** [comment]
就是这样。NIS 本身包含锐化，不需要加 NVSharpen。另外 NIS 和 NVSharpen 都很锐利，我放的对比图里 sharpness 为 0.2

**Comment by Blinue** [comment]
NIS 有明显振铃，不知道是本身就有还是移植产生的问题。NIS 缩放步骤和 lanczos 类似，或许也可以引入 lanczos 的抗振铃方法

**Comment by hooke007** [comment]
对比了LS的nis实现（同样的默认0.5锐化强度）
ls的nis问题更严重点，不光是振铃(更明显)，还出现了像素偏移。
magpie也会出现四周亮边
ls fsr
![LS FSR](https://user-images.githubusercontent.com/41094733/143876581-98c32cd6-bc05-418f-899d-495e90205562.png)
ls nis
![LS NIS](https://user-images.githubusercontent.com/41094733/143876618-079029e7-ff7f-4392-88a6-454e5b4201cb.png)
magpie nis
![magpie nis](https://user-images.githubusercontent.com/41094733/143876630-61ef733d-b177-46e1-82bd-0bc54f56fcb6.png)

**Comment by Blinue** [comment]
看起来 LS 的 NIS 实现有问题。

从我之前放的对比图上看 https://imgsli.com/ODM4Mzg ，NIS 没亮边，也没像素偏移。你换一种捕获方式看看

**Comment by hooke007** [comment]
亮边和偏移不算普遍问题，一般程序也不会触发，复现条件还挺苛刻的，既要有自带黑边还得是非常规比例....

**Comment by hooke007** [comment]
我观察了一下你们的图，自己也测了一下，又有了新的发现，这回反而是ls表现稍好点。（全部设定锐化为0减少干扰，也尝试了不同捕获方式）

magpie的四周收缩不均匀（左侧和上方收的更多，这和它 https://github.com/Blinue/Magpie/issues/202#issuecomment-981638572 左上出现亮边的方向一致），锐化感更强
![Snipaste_2021-11-30_07-47-01](https://user-images.githubusercontent.com/41094733/143961008-4962f9da-6461-4d24-83a9-7042b867335c.jpg)
LS的四周收缩程度一致且不大（这和它 https://github.com/Blinue/Magpie/issues/202#issuecomment-981638572 四周出现亮边的方向一致，几乎可以忽略因为lanczos也是差不多表现），但更严重的文字彩边
![Snipaste_2021-11-30_07-49-35](https://user-images.githubusercontent.com/41094733/143961219-b5576948-b6cd-419b-bba0-83dc36f6050e.jpg)

_nis的放大确实遗传了lanczos的毛病，文字笔画（特别是“后”字）中间的部分颜色区块丢失了。_

**Comment by Blinue** [comment]
palxex 放出截图四周是均匀的
![image](https://user-images.githubusercontent.com/34770031/143964674-9fb3b0bb-626b-4023-a632-d580e7c1b4a0.png)

这个 bug 什么时候会出现

**Comment by hooke007** [comment]
win10下是均匀的，我猜它的工作电脑应该是win10

**Comment by Blinue** [comment]
[PrintWindow](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-printwindow) 有一个未记录的参数 PW_RENDERFULLCONTENT 可以捕获到 UWP 窗口，或许又能增加一种捕获方式

**Comment by Blinue** [comment]
> 这个奇葩测试我在win10下也跑了，不出意外，四周均匀的出现了亮边。。。图我就不传占楼了（和 LS nis类似）

我会调查一下这个问题

**Comment by Z-Dante** [comment]
Not sure if this is reproduceable, but I couldn't get RTSS overlays to work on any of the v0,8 dev versions. Last version where it works perfectly is v0.7.1.

**Comment by Blinue** [comment]
This issue may be related to .net 6, I'm trying to fix it

**Comment by Blinue** [comment]
@hooke007  NIS 偏移问题已经被修复了

**Comment by palxex** [comment]
嗯……刚看到
之前我办公电脑上的测试没留截图，看了看应该是Win11 Dev上的。那台电脑Win10上没装2022，没.net6开发环境。
另外我这边0.8 dev上afterburner看起来还算正常。0.7 dev时有游戏和magpie俩overlay，当前dev上没留意什么时候后者没了，但游戏本身的rtss overlay还是会bake到游戏截图里被magpie放大出来。

**Comment by Blinue** [comment]
RTSS 现在无法检测到 Magpie，对一些人是好事，对一些人是坏事

**Comment by hooke007** [comment]
> NIS 偏移问题已经被修复了

确实，现在的亮边很均匀，这个算nis的自身缺陷没救了吧

**Comment by Blinue** [comment]
我怀疑是否需要支持功能级别10.x，都是十年前的老显卡，但支持它们需要很多额外工作。以后会添加的计算着色器也不支持

**Comment by linserv33** [comment]
个人认为如果是十年前的老显卡，对于2D游戏的窗口放大还是有一定帮助的，但是对于现代3D游戏来说无济于事（特别是3A）

**Comment by hooke007** [comment]
可以另外保留一个只提供简单算法的版本（不加功能只维护），10年前的设备跑jinc这种传统算法都不轻松，更别说自适应锐化了。

**Comment by Blinue** [comment]
我的计划是v0.8额外发布一个dx10的版本作为最后的支持。因为我精力有限，这个版本不会有太多维护

v0.9 开始支持计算着色器

**Comment by Blinue** [comment]
发现一个很有意思的参数 [WDA_EXCLUDEFROMCAPTURE](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setwindowdisplayaffinity)

Magpie 捕获方法中最大的限制是要能捕获到被遮住的窗口，这个参数意味着更多可能性

**Comment by Blinue** [comment]
新加入的 Desktop Duplication 捕获方法可以捕获到 UWP 窗口，但是 GPU 占用比其他方法高不少

**Comment by laincat** [comment]
保存，选择，某一个程序的 设置 方案？

**Comment by Blinue** [comment]
> 保存，选择，某一个程序的 设置 方案？

如果你指的是针对特定游戏的配置，暂时不会有这个功能

**Comment by Blinue** [comment]
crt-royale 太难啃了，我决定放弃。它应该集成在模拟器里，因为对输入的要求很苛刻

**Comment by Blinue** [comment]
我会再移植几个 crt 着色器，crt-royale 搞多了，现在看什么着色器都眉清目秀

**Comment by Blinue** [comment]
MagpieFX 现已支持获取总帧数和光标位置，因此可以实现一些炫酷的动画效果！

**Comment by Blinue** [comment]
曼德博集合
``` hlsl
//!MAGPIE EFFECT
//!VERSION 1


//!CONSTANT
//!VALUE OUTPUT_WIDTH / OUTPUT_HEIGHT
float ratio;

//!CONSTANT
//!DYNAMIC
//!VALUE FRAME_COUNT
int frameCount;


//!PASS 1
//!BIND INPUT

int mandelbrot(float2 c) {
	float2 z = c;
	for (int i = 0; i < 1500; i++) {
		if (dot(z, z) > 4.0) return i;
		z = float2(z.x * z.x - z.y * z.y, 2.0 * z.x * z.y) + c;
	}
	return 0;
}

float zoom(float t) {
	float a = floor(t / 24.0f);
	return (exp(-t + 24.0 * a) + exp(t - 24.0 - 24.0 * a));
}

float4 Pass1(float2 pos) {
	pos.x = pos.x * ratio - 0.2;
	float2 c = ((pos * 2 - 1) * 2.0) * zoom(frameCount / 100.0f);
	c += float2(-1.253443441, 0.384693578);
	float iters = float(mandelbrot(c));

	float3 col = sin(float3(0.1, 0.2, 0.5) * float(iters));
	return float4(col, 1.0);
}

```

**Comment by Blinue** [comment]
终于找到了 Graphics Capture 无法捕获一些窗口的原因。WGC 只能捕获在 Alt+Tab 列表中的窗口。解决办法也很简单，修改源窗口的样式使它可以被 alt+tab 切换到就完了

**Comment by Blinue** [comment]
WGC 高 CPU 占用的问题似乎是 directflip 引起的，你们尝试一下关闭 directflip 看看 cpu 占用 @palxex @hooke007

**Comment by hooke007** [comment]
可以降低近一半的单线程负载
![Snipaste_2021-12-17_00-46-14](https://user-images.githubusercontent.com/41094733/146413575-530bed18-672d-4085-9e1c-bb52b3cfda63.jpg)
![Snipaste_2021-12-17_00-47-12](https://user-images.githubusercontent.com/41094733/146413520-f8f88a84-a708-489a-97a7-1a4290ce12a7.jpg)

**Comment by Blinue** [comment]
OBS 的 WGC CPU 占用很少，但是我按他们的方法配置也没解决问题

**Comment by hooke007** [comment]
我这里比较下来obs倒也不少
![obs](https://user-images.githubusercontent.com/41094733/146474873-84649a93-b25f-42f4-ae2c-2d6da89544dc.jpg)

magpie关闭directflip，缩放设置为nearest [1,1]来模拟obs纯捕捉
![magpie](https://user-images.githubusercontent.com/41094733/146474947-fbd74297-2765-4071-8c89-f2ef05e24f51.jpg)

**Comment by Blinue** [comment]
关于跨越多个屏幕的功能有一个意想不到的障碍，Windows 没提供 API 持久标记一个显示器（如 ID 之类的），我就没法让用户指定使用哪些显示器。

这个问题存在十多年了 https://social.msdn.microsoft.com/Forums/en-US/668e3cf9-4e00-4b40-a6f8-c7d2fc1afd39/how-can-i-retrieve-monitor-information?forum=windowsgeneraldevelopmentissues

设置里每个显示器都有一个编号，但不幸的是，这个编号没有 API 来获取，而且系统重启后编号可能会变...

不值得在这里花太多功夫，我就只提供一个“跨越所有显示器”的功能

**Comment by FineLine0** [comment]
custom scaling algorithim? less intensive scaler than magpie fsr but better than bilinear and bicubic

**Comment by Blinue** [comment]
Do you want to recommend a new effect? Please file an issue

**Comment by palxex** [comment]
我这里并没有出现过WGC占满CPU的情况，应该是因为我的显卡并不支持DirectFlip导致。在测试中打开关闭Magpie的DirectFlip选项都不影响CPU占用率。

**Comment by Blinue** [comment]
光标可以在屏幕间自由移动真的很棒，可惜我只有一个显示器，无福消受了🥲

**Comment by hooke007** [comment]
NIS 更新到了1.0.1

**Comment by Blinue** [comment]
会跟进

**Comment by Blinue** [comment]
NIS 更新后振铃问题好了很多

**Comment by hooke007** [comment]
nvsharpen 有往左上偏移的问题
sharpeness都是0.5

nis
![nis](https://user-images.githubusercontent.com/41094733/147391125-2abd7a69-ae8f-4b1e-a655-2424647bdcc2.jpg)

nvsharpen
![nvsharpen](https://user-images.githubusercontent.com/41094733/147391135-2068a298-6634-4c15-b964-8858225e95c8.jpg)

变形后 nvsharpen
![bilinear+nvsharpen](https://user-images.githubusercontent.com/41094733/147391128-8a9f42db-0770-41ed-ab58-0687f061f238.jpg)

**Comment by hooke007** [comment]
Finesharp无法修改子参数
`2021-12-26 02:40:04.244|warning|Renderer.cpp:Renderer::CompileShader|编译像素着色器时产生警告：C:\Users\hooke\Desktop\magpie_preview\Pass1(38,2): warning X4000: use of potentially uninitialized variable (blur_ori)`

**Comment by Blinue** [comment]
> nvsharpen 有往左上偏移的问题

这个问题似乎一直有，我正在调查

**Comment by Blinue** [comment]
现有的效果里只有 FSR 不支持 DX10，不用发布 DX10 版本了，直接加一个 DX10 的 FSR 就好。

**Comment by Blinue** [comment]
因为现在路线图迁移到 Projects 了，接下来关于开发的讨论转移到 Discussions 里

**Comment by Blinue** [comment]
#254
