### ISSUE TITLE
v0.7 计划

### ISSUE THREAD

**Issue by Blinue** [Blinue/Magpie#94]
### 功能

- [x] 重写效果引擎
- [x] 实现编译缓存
- [x] 移植现有着色器
- [x] 移植 Anime4K v4
#87 
- [x] 移植像素画缩放算法（XBRZ等）
#62 
#103 
- [x] 支持在 3D 游戏中限制光标
#140
- [x] 提供不绘制光标的功能
#121 
- [x] 支持以管理员权限启动
#64 
- [x] 移植 FXAA 和 SMAA
#74 
- [x] 检测源窗口 DPI
- [x] 提供关闭低延迟模式的功能（只适用于垂直同步）
- [x] 支持缩放光标
#124 
- [ ] ~~提供快捷键将鼠标从游戏中释放和重新捕获~~（暂时不实现）
- [x] 提供关闭 DirectFlip 的功能
#166 
- [x] 根据任务栏颜色自动切换图标
#131

### BUG

- [x] 黑色背景下部分缩放算法绿边问题
#168 

### 其他

- [x] All Contributors
- [x] 移除 Hardcodet.NotifyIcon.Wpf 依赖，因为它不兼容 GPLv3
- [x] 贡献指南

**Comment by Blinue** [comment]
现在Magpie使用[Direct2D Custom Effect](https://docs.microsoft.com/en-us/windows/win32/direct2d/custom-effects)实现缩放效果，这个技术不是为性能而设计的，因此我计划使用Direct3D重写效果引擎，以实现下面的目标：

1. 精细管理GPU指令和资源以提升性能和降低显存占用。
2. 支持更多分辨率，Direct3D对纹理的限制比Direct2D少的多。
3. 通过在运行时编译着色器实现效果插件化。
4. 游戏内更改缩放配置。

这些是长远的目标，v0.7将至少实现第一条。

另外我也在考虑对reshade的兼容性。reshadeFX虽然是独立的组件，但它和reshade本身紧密耦合，因此短期内不会支持。

**Comment by Blinue** [comment]
目前已知的一些提升性能的方法：

1. 提高 Magpie 的进程优先级。
2. 关闭游戏模式。有时游戏模式会使 OS 分配更多 GPU 资源给游戏本身。
3. 在 GPU 驱动中提高 Magpie 的优先级或降低游戏的优先级。
4. 如果有多个 GPU，可以让 Magpie 运行在其他 GPU 上。
5. 注意显存占用，在显存不足时 Magpie 会卡顿。

**Comment by Koteusz** [comment]
There is also Win32.DwmThumbnail capturing method which is fast. There is a comparison and samples [here](https://github.com/mika-sandbox/dotnet-window-capture)

**Comment by Blinue** [comment]
DwmThumbnail cannot get the texture of the window, it is drawn directly by DWM.

DwmSharedSurface seems to be a good method, although it is an undocumented API.

**Comment by hooke007** [comment]
一个可有可无的不要紧的图标问题
![Snipaste_2021-09-03_00-04-02](https://user-images.githubusercontent.com/41094733/131878669-94305604-3eb1-4867-bd8f-dec95f5c279f.jpg)
magpie的后台图标在深色和背景下任务栏很难看见，虽然截图可见性尚可，但是受限于实际的显示设备的亮度和对比度

**Comment by Blinue** [comment]
现在的图标太简陋了，如果有人能贡献图标就好了

**Comment by HealGea** [comment]
If it is not too much work for you, can you translate the road map and other things to English too? I am very curious as I am very interested in the program. Thanks.

**Comment by LightMu** [comment]
- https://imgtu.com/i/hR1iVI

**Comment by LightMu** [comment]
> 现在的图标太简陋了，如果有人能贡献图标就好了

https://imgtu.com/i/hR1iVI 自己P了个

**Comment by LightMu** [comment]
64x 512x ICO

**Comment by LightMu** [comment]
64x 512x ico      https://wwa.lanzoui.com/iDy3dtmj05a

**Comment by LightMu** [comment]
> > 现在的图标太简陋了，如果有人能贡献图标就好了
> 
> https://imgtu.com/i/hR1iVI 自己P了个

https://wwa.lanzoui.com/iWEq4tmj5fa    ICO格式

**Comment by LightMu** [comment]
https://imgtu.com/i/hR1bQg效果

**Comment by LightMu** [comment]
https://imgtu.com/i/hR1bQg    效果

**Comment by Blinue** [comment]
谢谢，这个图标很棒。现在的问题是它在显示为32x32的场合太糊（比如系统托盘）
![屏幕截图 2021-09-05 090829](https://user-images.githubusercontent.com/34770031/132111724-3db321d2-0d8f-4f6c-972b-919f61346948.png)
文字已经不可见了。我的想法是图标要尽量简洁抽象，在尺寸较小时也有很高辨识度（比如图上的TrafficMonitor和Shadowsocks）。希望你能再做一些工作，为小尺寸的图标进行优化

**Comment by Blinue** [comment]
@HealGea Thanks for the suggestion. I'm putting more effort into coding than localizing the documentation. But if someone contributes a translation I'll be happy to accept it.

**Comment by LightMu** [comment]
> 谢谢，这个图标很棒。现在的问题是它在显示为32x32的场合太糊（比如系统托盘）
> ![屏幕截图 2021-09-05 090829](https://user-images.githubusercontent.com/34770031/132111724-3db321d2-0d8f-4f6c-972b-919f61346948.png)
> 文字已经不可见了。我的想法是图标要尽量简洁抽象，在尺寸较小时也有很高辨识度（比如图上的TrafficMonitor和Shadowsocks）。希望你能再做一些工作，为小尺寸的图标进行优化

https://imgtu.com/i/hRfh0H 会不会太简单

**Comment by Blinue** [comment]
虽然很有设计感，但对比度太低了
![image](https://user-images.githubusercontent.com/34770031/132116083-0f3379a1-5183-403e-95a2-34b3d22c10cf.png)
![image](https://user-images.githubusercontent.com/34770031/132116100-242193ac-076e-4662-96da-cc909be39760.png)

分享一个制作图标的软件，现在的图标就是用它做的。Windows的图标需要32x32，48x48，64x64，128x128四种尺寸，建议分别导出然后整合到ico里。
[IcoFX.zip](https://github.com/Blinue/Magpie/files/7110960/IcoFX.zip)

感谢，完成之后请提交pull request，这样可以把你加入贡献者名单 :)

**Comment by LightMu** [comment]
> 虽然很有设计感，但对比度太低了
> ![image](https://user-images.githubusercontent.com/34770031/132116083-0f3379a1-5183-403e-95a2-34b3d22c10cf.png)
> ![image](https://user-images.githubusercontent.com/34770031/132116100-242193ac-076e-4662-96da-cc909be39760.png)
> 
> 分享一个制作图标的软件，现在的图标就是用它做的。Windows的图标需要32x32，48x48，64x64，128x128四种尺寸，建议分别导出然后整合到ico里。
> [IcoFX.zip](https://github.com/Blinue/Magpie/files/7110960/IcoFX.zip)
> 
> 感谢，完成之后请提交pull request，这样可以把你加入贡献者名单 :)



> 虽然很有设计感，但对比度太低了
> ![image](https://user-images.githubusercontent.com/34770031/132116083-0f3379a1-5183-403e-95a2-34b3d22c10cf.png)
> ![image](https://user-images.githubusercontent.com/34770031/132116100-242193ac-076e-4662-96da-cc909be39760.png)
> 
> 分享一个制作图标的软件，现在的图标就是用它做的。Windows的图标需要32x32，48x48，64x64，128x128四种尺寸，建议分别导出然后整合到ico里。
> [IcoFX.zip](https://github.com/Blinue/Magpie/files/7110960/IcoFX.zip)
> 
> 感谢，完成之后请提交pull request，这样可以把你加入贡献者名单 :)

https://wwa.lanzoui.com/iBxBatmtxjc

**Comment by HealGea** [comment]
> @HealGea Thanks for the suggestion. I'm putting more effort into coding than localizing the documentation. But if someone contributes a translation I'll be happy to accept it.

I would be more than happy to help you if I know the language you speak but I don't. I can translate the program from English to Turkish though if you are interested.

**Comment by Blinue** [comment]
Feel free to contribute translations, and it would be better if you can maintain it.

**Comment by HealGea** [comment]
> Feel free to contribute translations, and it would be better if you can maintain it.

Do you have something like Discord so I can contact you about translation?

**Comment by Blinue** [comment]
You should open a pull request or discussion.

**Comment by Blinue** [comment]
渲染的重写已经基本完成，希望你们帮忙测试一下d3d分支的性能 @palxex @hooke007

现在只支持FSR，且只能放大到全屏，缩放模式不起作用。

WinRT捕获重命名为 GraphicsCapture，添加了 DwmSharedSurface 和 GDI Over DXGI 两种捕获方式。希望你们分别测试四种捕获方式的性能。

**Comment by hooke007** [comment]
>DwmSharedSurface 和 GDI Over DXGI
暂时没有感知上的延迟

**Comment by Blinue** [comment]
测试不同类型的窗口（GDI、DirectX、OpenGL等），查看CPU和GPU占用。GDI有延迟吗

**Comment by Blinue** [comment]
GraphicsCapture 是最快的，就是CPU占用有点高，DwmSharedSurface 和 GDI Over DXGI 比较平衡，而且可以捕获到更多类型的窗口，GDI性能最差。

和v0.6.1相比怎么样

**Comment by hooke007** [comment]
这次直接对任务管理器进行放大观察，基本符合你的描述
从左到右: 源   GC   DSS   GDI+   GDI
![Snipaste_2021-09-15_20-28-12](https://user-images.githubusercontent.com/41094733/133435200-03932699-7ee2-424e-8b37-ce4143db9674.jpg)
正好几次测试都调用了cpu0，GC的cpu占用很浮夸，gdi的gpu占用最明显

**Comment by palxex** [comment]
主观感受上这四种区别不大。
延迟方面，因为个人不敏感没法说。跟之前测试环境一样，zen2 3600锁4G，RX580 4G，显示器4k60hz无freesync。
因为该版本帧率显示不生效，用AfterBurner显示的结果是会出现两个，原游戏画面和Magpie放大过的。
原神——游戏内设置1080P+60fps，垂直同步开：
GC和GDI这两个，两边帧率是同步的，一般是60。
DwmSharedSurface 和 GDI Over DXGI 这两个则不同，游戏本身的帧率保持60的前提下，Magpie窗口的帧率会随着负载减小越来越高，我在个别UI中见到了接近300的fps，估计是没有VSync限制
CEMU+BOTW——GraphicsPack设置（模拟器特有的hack，强制设置3d相关分辨率）1080P+60fps，垂直同步开：
4个方法都保持了绝大多数地方两者一致，除了开头UI很反常的，游戏内60fps，Magpie 30fps.
游戏内通过AfterBurner观察实时CPU占用大致符合作者的概述，但总体上都不算高，只看第一个核心没有见到超过40%的时候，GDI over DXGI最低（如果VSync能生效——因为在我的60hz显示器上渲染到300帧并无意义——我猜还能更低）。GPU我的设置下一直都是接近满载的。
该分支比起0.6.1正式版，显存占用明显大大降低，1080P->4K大概不到100M，4K->4K约200M出头（前面的是cemu的窗口化全屏4k，相当于主流游戏的4K 50%渲染），而显存不爆的情况下，cemu+botw也不再有之前版本的不明帧率降低。
以上都是Win10下的测试结果，Win11的结果（包括圆角问题是否仍然存在）需要等明晚测试后再更新。

**Comment by Blinue** [comment]
感谢这么详细的测试。垂直同步是始终开启的，Magpie的帧率受系统控制，所以高帧率的一个可能是系统不限制帧率，或者是AfterBurner的显示问题，等我实现了FPS显示再做定论。

我想把你加入贡献者名单，但你要提交 commit 才行，比如编辑 README。

**Comment by palxex** [comment]
Win11圆角的问题，经过测试两个新的捕获模式都不存在问题（GDI也不存在问题，可能是之前没有测过？）。现在只有GraphicsCapture模式有左右下角圆角模糊的问题。
对本项目现在我就是个纯用户，通过测试反馈对开发有帮助就很满足了:) 有能力贡献代码时再说吧。
后续参与者多了的话，可以考虑参考其他开源软件在仓库中加入AUTHORS/CREDITS文件，对maintainer和contributor加以注明即可。

**Comment by Blinue** [comment]
每个花时间帮助这个项目的人都是贡献者，代码不是唯一重要的。我正在考虑使用 [All Contributors](https://allcontributors.org/)

**Comment by hooke007** [comment]
d3d的gdi使用一天下来确信没延迟问题；

目前为止好像没见到人使用uwp/wpf程序的反馈，这种情况几乎只有GC可用，其它方法几乎无法捕获该类窗口

**Comment by Blinue** [comment]
WPF没有问题，Magpie用户界面就是WPF。

UWP只有GC可用，这种窗口无法用通常的方法捕获到，而且无法裁剪它的边框。UWP的窗口其实是“无边框”的，它的标题栏是自己绘制的，这样就可以添加返回和全屏按钮，要不要裁剪标题栏都是一个问题。

**Comment by PenguinDOOM** [comment]
I tried the d3d branch with warframe, but everything except GraphicsCapture only works when Optimized Flip Model is off.
Don't work with DirectX 12

**Comment by Blinue** [comment]
窗口绘制时一般都是绘制在由系统提供的”重定向表面“里，DWM在显示一帧时会从这个表面取像素，大部分捕获方式也都是取的这个表面。UWP窗口的不同之处是它设置了 [WS_EX_NOREDIRECTIONBITMAP](https://docs.microsoft.com/en-us/windows/win32/winmsg/extended-window-styles)，因此没有这个表面，而是直接将图像交给DWM合成。

GC之所以能捕获到UWP是因为它捕获到的是DWM合成后的图像，这是它和其他捕获方式最根本的不同之处。也正因如此，它在Win11中会捕获到圆角，因为圆角的处理就是在DWM中完成的。

虽然这是些技术细节，但如果有其他人遇到了这个问题，这些信息可能有用。

**Comment by Blinue** [comment]
'Optimized Flip Model' may use a similar technology to UWP.

**Comment by hooke007** [comment]
win32转uwp的微信 （win10）任何方法都能捕获圆角，这个圆角是怎么产生的

**Comment by Blinue** [comment]
微信是普通的无边框窗口，圆角是自己绘制的。win32转uwp本质上仍是win32

**Comment by hooke007** [comment]
测试了更多游戏，发现一个问题，d3d分支的光标会消失，目前只在wstar的美少女万华镜系列上发现这个issue
[Runtime.log](https://github.com/Blinue/Magpie/files/7189218/Runtime.log)

**Comment by RyzenAdvanced** [comment]
Adding these feature as wishlist for 0.7x revision:
https://github.com/Blinue/Magpie/discussions/153

**Comment by BattleAngel-99** [comment]
作者你好，希望能将项目的FSR优化一下 ，我在将FSR技术用于《COD18先锋》《 大表哥2》《原神》等等一些游戏中有明显的掉帧卡顿现象，我很喜欢你做的软件 利用FSR让我能够看清敌人，我希望作者能够继续坚持做下去谢谢！！！

**Comment by LightMu** [comment]
> 作者你好，希望能将项目的FSR优化一下 ，我在将FSR技术用于《COD18先锋》《 大表哥2》《原神》等等一些游戏中有明显的掉帧卡顿现象，我很喜欢你做的软件 利用FSR让我能够看清敌人，我希望作者能够继续坚持做下去谢谢！！！

只是希望提高辨识清晰度的话，建议你尝试驱动软件自带的锐化或者Reshade和虚幻引擎的锐化

**Comment by BattleAngel-99** [comment]
好的，我在试试其他的之前我也试过AMD自带的，不过感觉效果不尽人意



在 2021-09-24 11:15:52，"LightMu" ***@***.***> 写道：

作者你好，希望能将项目的FSR优化一下 ，我在将FSR技术用于《COD18先锋》《 大表哥2》《原神》等等一些游戏中有明显的掉帧卡顿现象，我很喜欢你做的软件 利用FSR让我能够看清敌人，我希望作者能够继续坚持做下去谢谢！！！

只是希望提高辨识清晰度的话，建议你尝试驱动软件自带的锐化或者Reshade和虚幻引擎的锐化

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Blinue** [comment]
d3d分支有卡顿现象吗？

**Comment by Blinue** [comment]
已添加 FPS 显示功能，麻烦测试一下垂直同步 @palxex

**Comment by palxex** [comment]
> 已添加 FPS 显示功能，麻烦测试一下垂直同步 @palxex

已测试，原神配置如上，magpie显示的fps与afterburner的全屏版相同（存在一定延迟但最终会趋同），都是GDI/GC稳60，DwmSharedSurface 和 GDI Over DXGI在130-140浮动（取决于场景，选的是比较简单的一个）

**Comment by palxex** [comment]
当前d3d分支最新提交在原神游戏内输入中文，弹出IME窗口后会出现一个新问题：全屏显示正常，但原来的窗口凸显到了前面，覆盖住了部分显示。手动切出再切入恢复正常（输入英文，无选择窗则无问题）。该问题在不同游戏内触发方式不同，巫师3（steam版）里只要通过magpie全屏就会直接触发（该游戏另有仅GC可用/HDR颜色不正等问题，但均非新增问题，不赘）。
经过git bisect，第一个出现该问题的提交是 519225eb 。经尝试将Runtime/App.cpp内
“取消置顶，这样可以使该窗口在最前”注释条目的当前实现(SetWindowPos)改回该提交前的旧实现（GetWindowStyle/SetWindowLong)可解决此问题。

**Comment by Blinue** [comment]
本意是为了使全屏窗口不再置顶，这样就不会遮住一些工具窗口。现在看来行不通，存在有时无法遮住源窗口的问题，最新提交改回去了。

**Comment by Blinue** [comment]
## 关于延迟的分析

使用 [PresentMon](https://github.com/GameTechDev/PresentMon) 测了一下，Magpie 的延迟在 16ms 以内，无论是哪种捕获模式

![屏幕截图(2012)](https://user-images.githubusercontent.com/34770031/135386269-3e5f90ae-e102-4ad9-a609-7327dcad8287.png)

因为 Magpie 创建的窗口覆盖整个屏幕，在支持的硬件上可以触发 [DirectFlip](https://devblogs.microsoft.com/directx/dxgi-flip-model/#whats-new-in-flip-model)，因此无需通过 DWM 合成。

这是某个窗口化游戏的延迟：
![image](https://user-images.githubusercontent.com/34770031/135387655-39c47e2c-123e-48a7-8a51-946b75713881.png)

分析一下它的延迟：
1. Present(1, 0) 会等待下一个垂直同步，<16ms 延迟
2. 窗口化程序会交由 DWM 合成，16ms 延迟
3. 交给屏幕驱动，在下一次垂直同步中显示，16ms 延迟

![未命名文件 (4)](https://user-images.githubusercontent.com/34770031/135391687-6161547c-fb13-486e-be14-526b2108aaa6.png)

与之相比，Magpie 的延迟：
1. Present(0, 0) 不等待垂直同步，无延迟
2. 支持 DirectFlip 时无需 DWM 合成，无延迟
3. 交给屏幕驱动，在下一次垂直同步中显示，<16ms 延迟

![未命名文件 (1)](https://user-images.githubusercontent.com/34770031/135391030-8d48f96b-1f19-4092-97ef-1d08083683bd.png)

剩下的问题是捕获到的窗口帧位于哪个阶段。经过测试，我认为是在 DWM 合成后，在屏幕上显示前，甚至诸如 GDI 捕获模式也是如此，尽管它捕获到的是 DWM 合成前的图像。

现在的流程：
![未命名文件 (7)](https://user-images.githubusercontent.com/34770031/135404260-432250b5-d65f-4c20-9798-5935c413c948.png)

在这种情况下，Magpie 和源窗口的图像是同步的。

几个限制：
1. 不支持 DirectFlip 和 Multi-plane overlays 的硬件依然会使用 DWM 合成，引入一帧延迟。
2. 渲染的光标始终有一帧延迟。

**Comment by linserv33** [comment]
意思是支持DirectFlip的情况下会比一般窗口模式延迟还低？不错的优化！

**Comment by palxex** [comment]
d3d分支Win11 Dev问题报告，DwmSharedSurface颜色异常，其他模式无问题。同一Build在Win10上同一模式显示正常。
昨天因为Win11临近发布将Beta换到了Dev发现的，更换前未发现异常，所以Win11正式版估计也不会有问题。

**Comment by Blinue** [comment]
DwmSharedSurface 是未记录的 API，微软不会维护它的可用性。如果Win11正式版也有这个问题，我会尝试修复。

**Comment by palxex** [comment]
好的。我先把以下两个模式的截图发一下，看有没有对此熟悉的人能直观的看出问题所在
GDI over DXGI:
![god](https://user-images.githubusercontent.com/58222/135803813-46b800e7-8821-4dc1-8382-98184e7c3b14.jpg)
DWMSharedSurface:
![dss](https://user-images.githubusercontent.com/58222/135803836-0c8943cc-3898-4ccf-85e2-95a20adb4138.jpg)

**Comment by palxex** [comment]
呃找到原因了，是色深异常。
之前归因错误，升dev后在新amd驱动里调成10bit pixel format后测试的。经测试win10里这么调也出现了同样的现象。将该选项关掉后就正常了。保留事故现场警醒后人吧- -
猜测dwmsharedsurface获取的画面是游戏输出的原始像素格式，而其它三个是合成后的rgb。

**Comment by Blinue** [comment]
实际上是因为Magpie不支持HDR，这是HDR10的格式。因为我的显示器没有这个功能，所以没法开发。刚完成对可变帧率的支持，然而我也没法测试。

**Comment by palxex** [comment]
> 实际上是因为Magpie不支持HDR，这是HDR10的格式。因为我的显示器没有这个功能，所以没法开发。刚完成对可变帧率的支持，然而我也没法测试。

Adaptive Sync吗，这个我也没有硬件，建议可以开个征集测试。
HDR10我倒是可以测试，但不知道怎么做。有没有相关文档？

**Comment by Blinue** [comment]
HDR是比较高级的主题。[这里](https://github.com/walbourn/directx-vs-templates/blob/master/d3d11game_win32_dr/DeviceResources.cpp)是一个使用HDR的例子。[这里](https://docs.microsoft.com/en-us/windows/win32/direct3darticles/high-dynamic-range)是微软提供的文档，但实现时不用这么复杂，最主要的简化是不需要 tonemapping 支持。

**Comment by Blinue** [comment]
暂定语法

``` hlsl
//!MAGPIE EFFECT
//!VERSION 1
//!OUTPUT_WIDTH INPUT_WIDTH * 2
//!OUTPUT_HEIGHT INPUT_HEIGHT * 2

// 如果不定义 OUTPUT_WIDTH 和 OUTPUT_HEIGHT 表示此 Effect 可以接受任何大小的输出

// 计算表达式时有一些预定义常量
// INPUT_WIDTH
// INPUT_HEIGHT
// INPUT_PT_X
// INPUT_PT_Y
// OUTPUT_WIDTH
// OUTPUT_HEIGHT
// OUTPUT_PT_X
// OUTPUT_PT_Y
// SCALE_X
// SCALE_Y


// 变量定义
// 含有 VALUE 关键字的变量会填充该表达式的值
// 否则为在运行时可以改变的参数


//!CONSTANT
//!VALUE INPUT_WIDTH
int inputWidth;

//!CONSTANT
//!VALUE INPUT_HEIGHT
int inputHeight;

//!CONSTANT
//!VALUE SCALE_X
float scaleX;

//!CONSTANT
//!VALUE SCALE_Y
float scaleY;

//!CONSTANT
//!DEFAULT 0
//!LABEL 锐度
float sharpness;

// 纹理定义
// INPUT 是特殊关键字
// INPUT 不能作为 Pass 的输出

//!TEXTURE
Texture2D INPUT;

//!TEXTURE
//!WIDTH INPUT_WIDTH + 100
//!HEIGHT INPUT_HEIGHT + 100
//!FORMAT B8G8R8A8
Texture2D tex1;

// 采样器定义

//!SAMPLER
//!FILTER LINEAR
SamplerState sam1;

//!SAMPLER
//!FILTER POINT
SamplerState sam2;

// 所有 Pass 通用的部分

//!COMMON
#define PI 3.14159265359

// Pass 定义

//!PASS 1
//!BIND INPUT, sam1, sharpness
//!SAVE tex1
float func1() {
}

float4 Pass1(float2 pos) {
}

// 没有 SAVE 表示此 Pass 为 Effect 的输出

//!PASS 2
//!BIND tex1, sam2
float4 Pass2(float2 pos) {
}
```

**Comment by Blinue** [comment]
最新的提交需要SDK 22000，使用老版本可能无法编译

**Comment by login404** [comment]
> > Magpie是否使用MMCSS?
> > 其提供的Capture优先级比Games更高
> 
> 看了官方文档，有一些问题需要讨论：
> 
> 1. MMCSS 似乎只能调度 CPU，“GPU Priority”字段是不使用的。Magpie 并不是 CPU 密集型的程序，默认的 CPU 调度就足够了
> 2. MMCSS 服务似乎只在播放多媒体时启动
> 3. 一些人认为这个 API 是提升帧率的一种“奇技淫巧”，它对 Magpie 的作用仍需要测试
> 4. 相比"Capture"，一个未记录的配置“DisplayPostProcessing”是更适合Magpie的选择

提高调度优先级对降低延迟应该是有帮助的吧
似乎只要程序把线程注册给MMCSS就能用了
线程并不需要实际是多媒体
我是支持用DisplayPostProcessing的
不过有些人玩游戏时喜欢听歌 可能会抢资源

**Comment by Blinue** [comment]
feature/MMCSS 分支已经实现了这个功能。在我的测试里，对 GDI 的性能有一些提升，关闭垂直同步时最多可以提升 10 FPS，对其他的捕获模式没有明显提升。可能是因为 GDI 捕获模式对 CPU 最为依赖。

**Comment by Blinue** [comment]
我打算删除SSimSuperRes。SSimDownscaler会跟进。

**Comment by palxex** [comment]
报一个新发现的问题。
在测试以管理员方式自动启动时发现，magpie的选项勾选后是立刻生效的，但保存却不是（至少「不绘制光标」等好几个选项是这样的）。这导致修改配置后游戏可以以修改后的选项放大，但如果之后magpie被通过任务管理器kill掉，之前调好的配置将无法保存，下次启动还是修改前的状态。
而Win10的重启在我测试中是无法触发magpie的选项保存的，也许它的实现就是kill掉？这导致我只要修改magpie选项后不手动关闭magpie就重启，那配置修改就是白做的，除非我每次配置后就手动关掉magpie再启动一次再重启……
如果修改选项后立刻存储不容易/不方便做，建议改成提前到关闭选项页时就保存，或者加个跨所有配置选项页面的确定按钮也行。

**Comment by Blinue** [comment]
现在只在程序关闭时保存一次设置，我会改成在设置页关闭时保存

**Comment by Blinue** [comment]
dwmSharedSurface 现在可以无视 DPI 缩放，它可以捕获到系统执行缩放前的图像。希望你们测试一下 @hooke007 @palxex

**Comment by hooke007** [comment]
我当前环境暂无可以复现这个功能的程序。。如有将追加更新

**Comment by palxex** [comment]
测了一圈，目前手头只有少数几个2D游戏是DPI awareness可以测出区别，3D游戏包括模拟器（测试了原神、崩坏3、Okami、CEMU BOTW)似乎都是倾向于直接使用原生像素的，因此跟之前完全没有区别。
测试系统：Win10 21H1，系统设置缩放200%，游戏exe设置均取消「高DPI缩放替代」（否则所有游戏都会使用原生像素，忽略系统缩放配置）,magpie设置使用Integer Scale 2x
case 1. SDLPal. GraphicsCapture: 全屏后内容较窗口化后大一倍。DWMSharedSurface：全屏后所占屏幕空间较窗口化时完全一致。
case 2. Fate stay night/Fate Hollow Ataraxia. GraphicsCapture完全无效，DWMSharedSurface效果同上。

**Comment by Blinue** [comment]
DWMSharedSurface 和 GDI 捕获到的都是 DPI 缩放前的图像，因此不会有任何模糊。只有 GC 捕获到的是缩放后的。

因为使用了一些黑科技，无法确保它的可靠性，还需要更多的测试。主要看对客户区的裁剪是否正确（图像四周是否有非客户区，可能是白边或黑边）

**Comment by palxex** [comment]
已经测试的游戏里暂时没有发现此类情况，如果后续发现将追加到这个评论。

**Comment by biantaonkss** [comment]
大佬您好，我下载了您的0.7.0_preview1版本的Magpie，发现在有些游戏里当FSR锐度拉到最右边时画面会有很多像素点，并且左上角会出现两个afterburner，帧数也比较低
![1](https://user-images.githubusercontent.com/93912134/140722282-c2b2bab0-be53-40e9-a65c-b1da64d65ae1.png)
![2](https://user-images.githubusercontent.com/93912134/140722333-65dce7bb-933d-4ee7-adbb-1da65a94519a.png)
这两张是帝国时代2决定版和崩坏3的截图，但我在玩Minecraft的时候用同样的方法却没遇到这种情况，帧数得到了大幅提升，我手里只有这几款游戏，希望能有所帮助，请问这种问题是什么原因引起的呢？

**Comment by Blinue** [comment]
@biantaonkss 请在 #164 中反馈

**Comment by biantaonkss** [comment]
抱歉抱歉，我马上删掉





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Blinue/Magpie"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月8日(星期一) 晚上6:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Blinue/Magpie] v0.7 计划 (#94)





 
@biantaonkss 请在 #164 中反馈
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Blinue** [comment]
Magpie 应该有一套图标。

现在使用的是微软的 Segoe MDL2 Assets，有几个缺点：
1. 是字体图标，没法在系统托盘菜单中使用（Hardcodet.NotifyIcon.Wpf 可以使用，但它和 Magpie 许可证不兼容）
2. 只在 Win10/11 中提供，而在可能的情况下我想尽量向下兼容
3. 这套字体可能有许可证兼容性问题。一方面它随操作系统提供，可以视为是“系统软件”，但它本身是微软提供的商业字体。

另外 Magpie 的图标还没着落，我会加一个根据任务栏颜色自动切换图标的功能 #131

**Comment by nt-cubic** [comment]
![I605S@%(DDWBL2J}OF@N~%V](https://user-images.githubusercontent.com/88926027/141666090-b985fe1a-e019-47da-b0fe-ed5c57115e22.png)
我对logo有个想法。喜鹊（Magpie）的羽毛围成一个圈，作为放大镜的形意。
我画得有点复杂，大概风格使用这种：
![TGMBZ59VUA9BET$PM5%Q2~F](https://user-images.githubusercontent.com/88926027/141666137-12ed2c42-c8a5-4138-a83f-7a4dc30b93c8.png)
若是可以的话我托朋友整套logo出来

**Comment by Blinue** [comment]
感谢提出点子🙏

给Magpie做图标最棘手的问题是要适配系统托盘，这就要求：1. 简洁，在32x32的尺寸有辨识度 2. 同时适配黑底和白底，要么做成彩色，要么做出黑白两种版本

另外说一下 Magpie 名字的含义：mag 是放大镜，pie 是无限，字面意思就是“通用放大镜程序”，所以也可以写成MagPie。喜鹊是一个文字游戏，可以把这个名称“形象化”。Logo里有喜鹊的元素很好，没有也无妨

**Comment by hooke007** [comment]
https://github.com/Blinue/Magpie/issues/111

这个是不是在roadmap里被遗漏了

**Comment by Blinue** [comment]
这个功能有点复杂，0.8 里实现

**Comment by Blinue** [comment]
#202
